### numpy is a Python library used for working with arrays.

### It also has functions for working in domain of linear algebra, fourier transform and matrices
###

### Introduction:
###

In [2]:
import numpy as np

np.__version__

'1.24.3'

In [4]:
# 1-dim

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
type(a), a.shape, a.ndim, a.size

(numpy.ndarray, (4,), 1, 4)

In [6]:
# 0-dim

a = np.array(2)
a

array(2)

In [7]:
type(a), a.shape, a.ndim, a.size

(numpy.ndarray, (), 0, 1)

In [8]:
# 2-d

a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
 type(a), a.shape, a.ndim, a.size

(numpy.ndarray, (2, 3), 2, 6)

In [10]:
# 3-d

a = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[15,16,17]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [15, 16, 17]]])

In [11]:
type(a), a.shape, a.ndim, a.size

(numpy.ndarray, (2, 2, 3), 3, 12)