In [4]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[11,12,13],[14,15,16]])
c = np.array([[17,18,19],[20,21,22]])

np.concatenate([a,b])
np.concatenate([b,c])
np.concatenate([a,b,c])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [6]:
d = np.concatenate([a,b,c], axis = 1) # 1 refers to column wise
e = np.concatenate([a,b,c], axis = 0) # 0 refers to row wise

a,b,c,d,e


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[17, 18, 19],
        [20, 21, 22]]),
 array([[ 1,  2,  3, 11, 12, 13, 17, 18, 19],
        [ 4,  5,  6, 14, 15, 16, 20, 21, 22]]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19],
        [20, 21, 22]]))

In [7]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[11,12,13],[14,15,16]])
c = np.array([[17,18,19],[20,21,22]])

d = np.array([a,b,c])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[17, 18, 19],
        [20, 21, 22]]])

In [8]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[11,12,13],[14,15,16]])
c = np.array([[17,18,19],[20,21,22]])

np.vstack([a,c]),np.hstack([a,c])

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [17, 18, 19],
        [20, 21, 22]]),
 array([[ 1,  2,  3, 17, 18, 19],
        [ 4,  5,  6, 20, 21, 22]]))