In [2]:
# 1d-array

import numpy as np

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a[0], a[-1], a[-2], a[0:2], a[2:], a[:3]

(1, 4, 3, array([1, 2]), array([3, 4]), array([1, 2, 3]))

In [8]:
# 2d-array

import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
a[1]
a[0]
a[0,1], a[0,-2], a[1,0: 2]

(2, 3, array([5, 6]))

In [11]:
# 3d-array

a = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
a[0]
a[0,0]
a[0,0,0: 2], a[1,0,1:3]

(array([1, 2]), array([10, 11]))

###
## Creating Arrays:
###

In [14]:
import numpy as np

# 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# 2D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


###
## Advanced Slicing on 1D Arrays:
###

In [19]:
print(arr)

# Slicing from index 2 to the second last element
print("Slice from index 2 to second last element:", arr[2:-1])

# Slicing with a step of 3
print("Every third element:", arr[::3])

# Slicing the last three elements
print("Last three elements:", arr[-3:])


[10 20 30 40 50 60 70 80 90]
Slice from index 2 to second last element: [30 40 50 60 70 80]
Every third element: [10 40 70]
Last three elements: [70 80 90]


###
## Advanced Slicing on 2D Arrays:
###

In [23]:
print(arr_2d)

# Accessing the entire second row
print("\nSecond row:", arr_2d[1, :])   # arr_2d[1st row, start:end]

# Accessing the entire second column
print("\nSecond column:", arr_2d[:, 1])

# Accessing a subarray (rows 1 and 2, columns 2 and 3)
print("\nSubarray (rows 1 and 2, columns 2 and 3):\n", arr_2d[1:3, 2:4])

# Accessing elements using negative indices
print("\nElement at (-1, -2):", arr_2d[-1, -2])

# Reversing the order of rows
print("\nReversed rows:\n", arr_2d[::-1, :])

# Reversing the order of columns
print("\nReversed columns:\n", arr_2d[:, ::-1])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Second row: [5 6 7 8]

Second column: [ 2  6 10]

Subarray (rows 1 and 2, columns 2 and 3):
 [[ 7  8]
 [11 12]]

Element at (-1, -2): 11

Reversed rows:
 [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

Reversed columns:
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


###
## Boolean Indexing:
###

In [24]:
# Creating an array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Boolean indexing to select elements greater than 50
print("Elements greater than 50:", arr[arr > 50])

# Boolean indexing to select even elements
print("Even elements:", arr[arr % 2 == 0])

# Boolean indexing in 2D array to select elements greater than 5
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Elements greater than 5:\n", arr_2d[arr_2d > 5])


Elements greater than 50: [60 70 80 90]
Even elements: [10 20 30 40 50 60 70 80 90]
Elements greater than 5:
 [ 6  7  8  9 10 11 12]


###
## Fancy Indexing:
###

In [26]:
# Creating an array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(arr)

# Accessing elements at specific indices
indices = [0, 2, 4, 6]
print("Elements at indices 0, 2, 4, 6:", arr[indices])

# Using fancy indexing in a 2D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
row_indices = [0, 2]
col_indices = [1, 3]
print("Elements at (0,1) and (2,3):", arr_2d[row_indices, col_indices])


[10 20 30 40 50 60 70 80 90]
Elements at indices 0, 2, 4, 6: [10 30 50 70]
Elements at (0,1) and (2,3): [ 2 12]


###
## Combining Indexing and Slicing:
###

In [27]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Accessing specific elements with slicing
print("Elements in the first two rows and the last two columns:\n", arr_2d[:2, -2:])

# Accessing specific rows and columns
rows = [0, 2]
cols = [1, 3]
print("Elements at specific rows and columns:\n", arr_2d[rows][:, cols])


Elements in the first two rows and the last two columns:
 [[3 4]
 [7 8]]
Elements at specific rows and columns:
 [[ 2  4]
 [10 12]]
