###### Data Types:
###### 1 - integer
###### 2 -  boolean
###### 3 - unsigned integer
###### 4 - float
###### 5 - complex float
###### 6 - timedelta
###### 7 - datatime
###### 8 - object
###### 9 - string
###### 10 - unicode string
###### 11 - fixed chunk of memory for other types ( void )
######


In [6]:
import numpy as np

a = np.array([1,2,3,4.0])
a, a.dtype

(array([1., 2., 3., 4.]), dtype('float64'))

In [40]:
# converting to string

import numpy as np

a = np.array([1,2,3], dtype = 'S')
a, a.dtype

(array([b'1', b'2', b'3'], dtype='|S1'), dtype('S1'))

In [11]:
# converting to string

import numpy as np

a = np.array(['apple','banana'], dtype = 'S')
a

array([b'apple', b'banana'], dtype='|S6')

In [19]:
# converting to integer

import numpy as np

a = np.array([[1.2,3,44,3.34],[11.11,11,1.1,1.11]], dtype = 'i')
a.dtype

dtype('int32')

In [25]:
# converting to integer

import numpy as np

a = np.array(['20','11'], dtype = 'i')
a, a.dtype

(array([20, 11], dtype=int32), dtype('int32'))

In [35]:
# converting to integer

import numpy as np

a = np.array(['20.234','11.987'], dtype = 'f')
b = a.astype('i')
b, b.dtype

(array([20, 11], dtype=int32), dtype('int32'))

In [28]:
# converting to float

import numpy as np

a = np.array(['20.10','11.29'], dtype = 'f')
a, a.dtype

(array([20.1 , 11.29], dtype=float32), dtype('float32'))

In [42]:
# converting to boolean

a = np.array([0,1,1,0,1,0], dtype = 'bool')
a

array([False,  True,  True, False,  True, False])

In [51]:
# sorting

a = np.array([1,23,4,5,64,1,2,31,11])
np.sort(a), np.sort(-a)

(array([ 1,  1,  2,  4,  5, 11, 23, 31, 64]),
 array([-64, -31, -23, -11,  -5,  -4,  -2,  -1,  -1]))