###
## Creating Arrays with NaN Values:
###

In [16]:
import numpy as np

# Creating a 1D array with NaN values
arr = np.array([1, 2, np.nan, 4, 5])
print("Array with NaN:", arr)

# Creating a 2D array with NaN values
arr_2d = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])
print("2D Array with NaN:\n", arr_2d)


Array with NaN: [ 1.  2. nan  4.  5.]
2D Array with NaN:
 [[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


###
## Identifying NaN Values:
###

In [17]:
# Identifying NaN values in a 1D array
nan_mask = np.isnan(arr)
print("NaN mask for 1D array:", nan_mask)

# Identifying NaN values in a 2D array
nan_mask_2d = np.isnan(arr_2d)
print("NaN mask for 2D array:\n", nan_mask_2d)


NaN mask for 1D array: [False False  True False False]
NaN mask for 2D array:
 [[False False  True]
 [False  True False]
 [False False False]]


###
## Replacing NaN Values:
###

In [18]:
# Replacing NaN values with zero in a 1D array
arr_filled = np.nan_to_num(arr, nan=0.0)
print("1D array with NaN replaced by 0:", arr_filled)

# Replacing NaN values with the mean of the array
mean_value = np.nanmean(arr)
arr_filled_mean = np.where(np.isnan(arr), mean_value, arr)
print("1D array with NaN replaced by mean:", arr_filled_mean)

# Replacing NaN values in a 2D array
arr_2d[np.isnan(arr_2d)] = 0
print("2D array with NaN replaced by 0:\n", arr_2d)


1D array with NaN replaced by 0: [1. 2. 0. 4. 5.]
1D array with NaN replaced by mean: [1. 2. 3. 4. 5.]
2D array with NaN replaced by 0:
 [[1. 2. 0.]
 [4. 0. 6.]
 [7. 8. 9.]]


###
## Removing NaN Values:
###

In [13]:
# Removing NaN values from a 1D array
arr_no_nan = arr[~np.isnan(arr)]
print("1D array with NaN values removed:", arr_no_nan)

# Removing rows with NaN values from a 2D array
arr_2d_no_nan = arr_2d[~np.isnan(arr_2d).any(axis=1)]
print("2D array with rows containing NaN values removed:\n", arr_2d_no_nan)


1D array with NaN values removed: [1. 2. 4. 5.]
2D array with rows containing NaN values removed:
 [[1. 2. 0.]
 [4. 0. 6.]
 [7. 8. 9.]]


###
## Calculating with NaN Values:
###

In [14]:
# Calculating the mean while ignoring NaN values
mean = np.nanmean(arr)
print("Mean ignoring NaN values:", mean)

# Calculating the sum while ignoring NaN values
sum_val = np.nansum(arr)
print("Sum ignoring NaN values:", sum_val)

# Calculating the max while ignoring NaN values
max_val = np.nanmax(arr)
print("Max ignoring NaN values:", max_val)


Mean ignoring NaN values: 3.0
Sum ignoring NaN values: 12.0
Max ignoring NaN values: 5.0
