In [23]:
# shape,reshape

import numpy as np

a = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
a.ndim,a.shape

a.reshape(1,16)
a.reshape(2,8)
a.reshape(2,2,4)
a.reshape(4,1,4)
a.reshape(1,4,4)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

######
###### Ravel:
######  This method returns a flattened 1D array. Unlike flatten, ravel returns a reference to the original array whenever possible. If the returned array is modified, it may affect the original array. 
######

In [47]:
# ravel

import numpy as np

a = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
a.ndim,a.shape

a.reshape(1,16)
a.reshape(2,8)
a.reshape(2,2,4)
a.reshape(4,1,4)
b = a.reshape(1,4,4)

b, b.ravel()

# proof

c = a.ravel()
c[0] = 2
c, a

(array([ 2,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([[[ 2,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]]))

######
###### Flatten:
###### This method returns a copy of the array collapsed into one dimension. It always returns a flat copy of the original array, regardless of its original shape
######

In [45]:
# flatten

import numpy as np

a = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
a.ndim,a.shape

a.reshape(1,16)
a.reshape(2,8)
a.reshape(2,2,4)
a.reshape(4,1,4)
b = a.reshape(1,4,4)

b, a.flatten()

# proof

c = a.flatten()
c[0] = 2
c, a

(array([ 2,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]]))

######
#### In summary, reshape is used to change the shape of an array, flatten returns a copy of the array collapsed into one dimension, and ravel returns a flattened 1D array, often as a reference to the original array.
######