###
## Arange:
###

In [1]:
import numpy as np

a = np.arange(1,11)
a

b = np.arange(1,11,2)
b

c = np.arange(1,11,3)
c

d = np.arange(1,11,4, dtype = 'float')
d

array([1., 5., 9.])

###
## linspace():
###

In [2]:
import numpy as np

np.linspace(1,15,5)
np.linspace(1,10,6)
np.arange(1,20,4, dtype = 'float')


array([ 1.,  5.,  9., 13., 17.])

###
## random():
###

In [3]:

import numpy as np
from numpy import random

random.randint(1,10)
random.randint(1,10,8)
random.uniform(1,10,8)

array([3.11944778, 5.46694806, 3.96341082, 2.68719388, 1.68575453,
       5.76608651, 2.30734089, 9.25524278])

###
## range:
###

In [4]:

import numpy as np

np.array(range(1,10))
np.array(range(1,10), dtype = 'float')
np.array(range(1,10), dtype = 'S')



array([b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9'], dtype='|S1')

###
## zeros:
###

In [5]:

import numpy as np

np.zeros([2,3])
np.zeros([4,3])
np.zeros([2,3,3])


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

###
## ones:
###

In [6]:

import numpy as np

np.ones([2,3])
np.ones([4,3])
np.ones([2,3,3])


array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

###
## tile:
###

In [9]:

import numpy as np

np.tile([1,2,3], 2)
np.tile([11,17,20], 4)


array([11, 17, 20, 11, 17, 20, 11, 17, 20, 11, 17, 20])

###
## repeat:
###

In [10]:
np.repeat([9,10,11,12],3)
np.repeat([17,11,29,32,43,82,9],2)

array([17, 17, 11, 11, 29, 29, 32, 32, 43, 43, 82, 82,  9,  9])