In [18]:
import numpy as np

a = np.array([[1,2,3,4],[51,26,37,48]])
np.where(a > 10)

b = np.where(a > 10)
a[b]

(array([1, 1, 1, 1], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [29]:
import numpy as np

a = np.array([[[11,101,12,43],[10,17,20,99]],[[1,10,98,100],[82,89,76,35]]])
index = np.where((a < 80 ) & ( a > 30 ))
a[index]

array([43, 76, 35])

In [37]:
import numpy as np

a = np.array([[[11,101,12,43],[10,17,20,99]],[[1,10,98,100],[82,89,76,35]]])
index = np.where(a == 35)
a[index]



array([35])

In [42]:
import numpy as np

a = np.array([[[11,101,12,43],[10,17,20,99]],[[1,10,98,100],[82,89,76,35]]])
index = np.where((a < 80 ) & ( a > 30 ))
a[index] = 0
a

array([[[ 11, 101,  12,   0],
        [ 10,  17,  20,  99]],

       [[  1,  10,  98, 100],
        [ 82,  89,   0,   0]]])

In [45]:
import numpy as np

a = np.array([[[11,101,12,43],[10,17,20,99]],[[1,10,98,100],[82,89,76,35]]])
a.max(), a.argmax(), a.min(), a.argmin()
# argmax() flattens the array in 1-d and then gives index of max\min value


(101, 1, 1, 8)